@taskId = 4a53fbea-f3a3-4139-854a-7bb6e51e79b7

### List all tasks
GET http://localhost:8000/tasks
Accept: application/json

###

### Create a new task
POST http://localhost:8000/tasks
Content-Type: application/json
Accept: application/json

{
  "title": "New Task"
}

###

### Get a single task
GET http://localhost:8000/tasks/{{taskId}}
Accept: application/json

###

### Update a task
PUT http://localhost:8000/tasks/{{taskId}}
Content-Type: application/json
Accept: application/json

{
  "title": "Learn Deno KV deeply",
  "done": true
}

###

### Delete a task
DELETE http://localhost:8000/tasks/{{taskId}}
Accept: application/json
